# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shomea/p/pauldu/Desktop/TDT4200/4/TDT4200-Assignment-4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shomea/p/pauldu/Desktop/TDT4200/4/TDT4200-Assignment-4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shomea/p/pauldu/Desktop/TDT4200/4/TDT4200-Assignment-4/CMakeFiles /home/shomea/p/pauldu/Desktop/TDT4200/4/TDT4200-Assignment-4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shomea/p/pauldu/Desktop/TDT4200/4/TDT4200-Assignment-4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gpurender

# Build rule for target.
gpurender: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gpurender
.PHONY : gpurender

# fast build rule for target.
gpurender/fast:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/build
.PHONY : gpurender/fast

src/common/lodepng.o: src/common/lodepng.cpp.o

.PHONY : src/common/lodepng.o

# target to build an object file
src/common/lodepng.cpp.o:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/common/lodepng.cpp.o
.PHONY : src/common/lodepng.cpp.o

src/common/lodepng.i: src/common/lodepng.cpp.i

.PHONY : src/common/lodepng.i

# target to preprocess a source file
src/common/lodepng.cpp.i:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/common/lodepng.cpp.i
.PHONY : src/common/lodepng.cpp.i

src/common/lodepng.s: src/common/lodepng.cpp.s

.PHONY : src/common/lodepng.s

# target to generate assembly for a file
src/common/lodepng.cpp.s:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/common/lodepng.cpp.s
.PHONY : src/common/lodepng.cpp.s

src/cpu/cpurasteriser.o: src/cpu/cpurasteriser.cpp.o

.PHONY : src/cpu/cpurasteriser.o

# target to build an object file
src/cpu/cpurasteriser.cpp.o:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/cpurasteriser.cpp.o
.PHONY : src/cpu/cpurasteriser.cpp.o

src/cpu/cpurasteriser.i: src/cpu/cpurasteriser.cpp.i

.PHONY : src/cpu/cpurasteriser.i

# target to preprocess a source file
src/cpu/cpurasteriser.cpp.i:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/cpurasteriser.cpp.i
.PHONY : src/cpu/cpurasteriser.cpp.i

src/cpu/cpurasteriser.s: src/cpu/cpurasteriser.cpp.s

.PHONY : src/cpu/cpurasteriser.s

# target to generate assembly for a file
src/cpu/cpurasteriser.cpp.s:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/cpurasteriser.cpp.s
.PHONY : src/cpu/cpurasteriser.cpp.s

src/cpu/utilities/OBJLoader.o: src/cpu/utilities/OBJLoader.cpp.o

.PHONY : src/cpu/utilities/OBJLoader.o

# target to build an object file
src/cpu/utilities/OBJLoader.cpp.o:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/utilities/OBJLoader.cpp.o
.PHONY : src/cpu/utilities/OBJLoader.cpp.o

src/cpu/utilities/OBJLoader.i: src/cpu/utilities/OBJLoader.cpp.i

.PHONY : src/cpu/utilities/OBJLoader.i

# target to preprocess a source file
src/cpu/utilities/OBJLoader.cpp.i:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/utilities/OBJLoader.cpp.i
.PHONY : src/cpu/utilities/OBJLoader.cpp.i

src/cpu/utilities/OBJLoader.s: src/cpu/utilities/OBJLoader.cpp.s

.PHONY : src/cpu/utilities/OBJLoader.s

# target to generate assembly for a file
src/cpu/utilities/OBJLoader.cpp.s:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/utilities/OBJLoader.cpp.s
.PHONY : src/cpu/utilities/OBJLoader.cpp.s

src/cpu/utilities/geometry.o: src/cpu/utilities/geometry.cpp.o

.PHONY : src/cpu/utilities/geometry.o

# target to build an object file
src/cpu/utilities/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/utilities/geometry.cpp.o
.PHONY : src/cpu/utilities/geometry.cpp.o

src/cpu/utilities/geometry.i: src/cpu/utilities/geometry.cpp.i

.PHONY : src/cpu/utilities/geometry.i

# target to preprocess a source file
src/cpu/utilities/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/utilities/geometry.cpp.i
.PHONY : src/cpu/utilities/geometry.cpp.i

src/cpu/utilities/geometry.s: src/cpu/utilities/geometry.cpp.s

.PHONY : src/cpu/utilities/geometry.s

# target to generate assembly for a file
src/cpu/utilities/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/cpu/utilities/geometry.cpp.s
.PHONY : src/cpu/utilities/geometry.cpp.s

src/gpu/utilities/OBJLoader.o: src/gpu/utilities/OBJLoader.cpp.o

.PHONY : src/gpu/utilities/OBJLoader.o

# target to build an object file
src/gpu/utilities/OBJLoader.cpp.o:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/gpu/utilities/OBJLoader.cpp.o
.PHONY : src/gpu/utilities/OBJLoader.cpp.o

src/gpu/utilities/OBJLoader.i: src/gpu/utilities/OBJLoader.cpp.i

.PHONY : src/gpu/utilities/OBJLoader.i

# target to preprocess a source file
src/gpu/utilities/OBJLoader.cpp.i:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/gpu/utilities/OBJLoader.cpp.i
.PHONY : src/gpu/utilities/OBJLoader.cpp.i

src/gpu/utilities/OBJLoader.s: src/gpu/utilities/OBJLoader.cpp.s

.PHONY : src/gpu/utilities/OBJLoader.s

# target to generate assembly for a file
src/gpu/utilities/OBJLoader.cpp.s:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/gpu/utilities/OBJLoader.cpp.s
.PHONY : src/gpu/utilities/OBJLoader.cpp.s

src/gpu/utilities/geometry.o: src/gpu/utilities/geometry.cpp.o

.PHONY : src/gpu/utilities/geometry.o

# target to build an object file
src/gpu/utilities/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/gpu/utilities/geometry.cpp.o
.PHONY : src/gpu/utilities/geometry.cpp.o

src/gpu/utilities/geometry.i: src/gpu/utilities/geometry.cpp.i

.PHONY : src/gpu/utilities/geometry.i

# target to preprocess a source file
src/gpu/utilities/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/gpu/utilities/geometry.cpp.i
.PHONY : src/gpu/utilities/geometry.cpp.i

src/gpu/utilities/geometry.s: src/gpu/utilities/geometry.cpp.s

.PHONY : src/gpu/utilities/geometry.s

# target to generate assembly for a file
src/gpu/utilities/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/gpu/utilities/geometry.cpp.s
.PHONY : src/gpu/utilities/geometry.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/gpurender.dir/build.make CMakeFiles/gpurender.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... gpurender"
	@echo "... edit_cache"
	@echo "... src/common/lodepng.o"
	@echo "... src/common/lodepng.i"
	@echo "... src/common/lodepng.s"
	@echo "... src/cpu/cpurasteriser.o"
	@echo "... src/cpu/cpurasteriser.i"
	@echo "... src/cpu/cpurasteriser.s"
	@echo "... src/cpu/utilities/OBJLoader.o"
	@echo "... src/cpu/utilities/OBJLoader.i"
	@echo "... src/cpu/utilities/OBJLoader.s"
	@echo "... src/cpu/utilities/geometry.o"
	@echo "... src/cpu/utilities/geometry.i"
	@echo "... src/cpu/utilities/geometry.s"
	@echo "... src/gpu/utilities/OBJLoader.o"
	@echo "... src/gpu/utilities/OBJLoader.i"
	@echo "... src/gpu/utilities/OBJLoader.s"
	@echo "... src/gpu/utilities/geometry.o"
	@echo "... src/gpu/utilities/geometry.i"
	@echo "... src/gpu/utilities/geometry.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

